name: Auto Commit

on:
  schedule:
    - cron: '55 16 * * *'  # 协调世界时(UTC)
  workflow_dispatch:  # 手动触发

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update log.md
      run: |
        echo "$(date) - 贝斯手离开我的第 $(( ( $(date +%s) - $(date -d "2023-09-07" +%s) )/(60*60*24)+1 )) 天" >> log.md

    - name: Commit and push
      run: |
        git config --global user.name ${{ secrets.USER_NAME }}
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git add .
        git commit -m "贝斯手离开我的第 $(( ( $(date -u +%s) - $(date -u -d "2023-09-07" +%s) )/(60*60*24)+1 )) 天"
        git push
